name: test_drive
description: A sample command-line application.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.3.1

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0
  web_socket_channel: ^2.1.0
  socket_io_client: ^3.0.0-beta.2

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
